src/Entity/Posting.php
<?php

namespace App\Entity;

use App\Repository\PostingRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PostingRepository::class)]
class Posting
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'postings')]
    #[ORM\JoinColumn(nullable: false)]
    private $user;

    #[ORM\Column(type: 'string', length: 255)]
    private $title;

    #[ORM\ManyToOne(targetEntity: Category::class, inversedBy: 'postings')]
    private $category;

    #[ORM\Column(type: 'text', length: 9999)]
    private $description;

    #[ORM\Column(type: 'string', length: 255, nullable: false)]
    private $image;

    #[ORM\Column(type: 'datetime', options:['default' => 'CURRENT_TIMESTAMP'])]
    private $executed_at;

    #[ORM\OneToMany(mappedBy: 'post', targetEntity: Comment::class)]
    private $comments;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->executed_at = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getExecutedAt(): ?\DateTimeInterface
    {
        return $this->executed_at;
    }

    public function setExecutedAt(\DateTimeInterface $executed_at): self
    {
        $this->executed_at = $executed_at;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setPost($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getPost() === $this) {
                $comment->setPost(null);
            }
        }

        return $this;
    }
}

src/Form/PostingType.php
<?php

namespace App\Form;

use App\Entity\Posting;
use App\Entity\Category;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class PostingType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('category', EntityType::class,[
                'class' => Category::class,
                'choice_label' => 'name'
            ])
            ->add('title', TextType::class ,['attr' => [ 'class' => 'form-control']])
            ->add('description', TextareaType::class ,[
                'attr' => array(
                    'class' => 'form-control'
                )
                ])
            ->add('image', FileType::class,
            [
                'label' =>'Select image to upload',
                'data_class' => null,
                'required' => false,
                
            ])
            // ->add('executed_at')
            // ->add('user')
            
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Posting::class,
        ]);
    }
}

src/Controller/Admin/PostingController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Posting;
use App\Form\PostingType;
use App\Repository\PostingRepository;
use DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/admin/posting')]
class PostingController extends AbstractController
{
    private $postingRepository;
    public function __construct(PostingRepository $postingRepository)
    {
       $this->postingRepository =  $postingRepository;
    }

    #[Route('/', name: 'app_posting_index', methods: ['GET'])]
    public function index(PostingRepository $postingRepository): Response
    {
        return $this->render('posting/index.html.twig', [
            'postings' => $this->$postingRepository->findAll()
        ]);
    }

    #[Route('/new', name: 'app_posting_new', methods: ['GET', 'POST'])]
    public function new(Request $request, PostingRepository $postingRepository): Response
    {
        $user = $this->getUser();
        $posting = new Posting();
        $form = $this->createForm(PostingType::class, $posting);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            // je récupére le fichies passé dans le form
            $image = $form->get('image')->getdata();
            // si il y a une image de chargée
            if ($image) {
                // je crée un nom unique pour cette image et je remet l'extension
                $img_file_name = uniqid() . '.' . $image->guessExtension();
                // enregistrer le fichier dans le dossier image 
                $image->move($this->getParameter('upload_dir'), $img_file_name);
                // je set l'object article
                $posting->setImage($img_file_name);
            } else {
                // si $image = null je set l'image par default
                $posting->setImage('defaultimg.jpg');
            }
            $date_jour = new DateTime();
            $posting->setExecutedAt($date_jour);
            $posting->setUser($user);
        //    $entityManager->persist($posting);
        //    $entityManager->flush();

            $postingRepository->add($posting);
            return $this->redirectToRoute('app_posting_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('posting/new.html.twig', [
            'posting' => $posting,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_posting_show', methods: ['GET'])]
    public function show(Posting $posting): Response
    {
        return $this->render('posting/show.html.twig', [
            'posting' => $posting,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_posting_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Posting $posting, PostingRepository $postingRepository): Response
    {
        $othername = $posting->getImage();
        $form = $this->createForm(PostingType::class, $posting);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
             // je récupére le fichies passé dans le form
             $image = $form->get('image')->getdata();
             // si il y a une image de chargée
             if ($image) {
                 // je crée un nom unique pour cette image et je remet l'extension
                 $img_file_name = uniqid() . '.' . $image->guessExtension();
                 // enregistrer le fichier dans le dossier image 
                 $image->move($this->getParameter('upload_dir'), $img_file_name);
                 // je set l'object article
                 $posting->setImage($img_file_name);
             } else {
                 // si $image = null je set l'image par default
                 $posting->setImage($othername);
             }
            $postingRepository->add($posting);
            return $this->redirectToRoute('app_posting_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('posting/edit.html.twig', [
            'posting' => $posting,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_posting_delete', methods: ['POST'])]
    public function delete(Request $request, Posting $posting, PostingRepository $postingRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$posting->getId(), $request->request->get('_token'))) {
            $postingRepository->remove($posting);
        }

        return $this->redirectToRoute('app_posting_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/posting/_delete_form.html.twig
<section class="container">
    <div class="row">
        <div class="col">
        <form method="post" action="{{ path('app_posting_delete', {'id': posting.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ posting.id) }}">
    <button class="btn">Delete</button>
</form>
        </div>
    </div>
</section>

templates/posting/_form.html.twig
{{ form_start(form) }}
<div class="container">
    {{ form_widget(form) }}
    <div class="text-center">
        <button class="btn btn-info ">{{ button_label|default('Save') }}</button>
    </div>
</div>
    
{{ form_end(form) }}

templates/posting/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Posting{% endblock %}

{% block body %}
    <h2>Edit Posting</h2>

    {{ include('posting/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_posting_index') }}">back to list</a>

    {{ include('posting/_delete_form.html.twig') }}
{% endblock %}

templates/posting/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Posting index{% endblock %}

{% block body %}
    <section class="container py-2">
        <div class="row">
            <div class="col">
             <h2 class="text-center">Posting index</h2>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Description</th>
                <th>Image</th>
                <th>Executed_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for posting in postings %}
            <tr>
                <td>{{ posting.id }}</td>
                <td>{{ posting.title }}</td>
                <td>{{ posting.description }}</td>
                <td><img src="{{asset('assets/images/' ~ posting.image)}}" alt=""></td>
                <td>{{ posting.executedAt ? posting.executedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_posting_show', {'id': posting.id}) }}">show</a>
                    <a href="{{ path('app_posting_edit', {'id': posting.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_posting_new') }}">Create new</a>
            </div>
        </div>
    </section>
   
{% endblock %}

templates/posting/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Posting{% endblock %}

{% block body %}
<section class="container py-3">
    <div class="row">
        <div class="col">
            <h2 class="text-center">Create new Posting</h2>

            {{ include('posting/_form.html.twig') }}

            <a href="{{ path('app_posting_index') }}">Back to list</a>
        </div>
    </div>
</section>
    
{% endblock %}

templates/posting/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Posting{% endblock %}

{% block body %}
    <h2>Posting</h2>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ posting.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ posting.title }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ posting.description }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ posting.image }}</td>
            </tr>
            <tr>
                <th>Executed_at</th>
                <td>{{ posting.executedAt ? posting.executedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_posting_index') }}">back to list</a>

    <a href="{{ path('app_posting_edit', {'id': posting.id}) }}">edit</a>

    {{ include('posting/_delete_form.html.twig') }}
{% endblock %}